name: Trochilidae build & tests
on: [push, pull_request]
jobs:
  build:
    name: Trochilidae (PHP ${{ matrix.php-versions }})
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.4', '8.2', '8.3', '8.4']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Docs: https://github.com/shivammathur/setup-php
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
      - name: phpize
        run: phpize
      - name: configure
        run: ./configure --enable-trochilidae
      - name: make
        run: make
      - name: make test
        run: echo "n\n" | make test
